# Generated by Django 6.0.2 on 2026-02-23 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Аты-жөнү')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Машыгуунун түрү')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Кардардын аты')),
                ('club', models.CharField(default='Tribe', max_length=100, verbose_name='Клуб')),
                ('zone', models.CharField(default='Cycle', max_length=100, verbose_name='Зона')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Башталышы')),
                ('duration_min', models.PositiveIntegerField(default=30, verbose_name='Узактыгы (мүнөт)')),
                ('is_automatic_start', models.BooleanField(default=False, verbose_name='Автоматтык старт')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.trainer', verbose_name='Тренер')),
                ('training_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.trainingtype', verbose_name='Тренировка')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписаниелер',
            },
        ),
    ]
