# Generated by Django 6.0.2 on 2026-03-01 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Аты-жөнү')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Машыгуунун түрү')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('competition', 'Соревнование'), ('workout', 'Произвольная тренировка')], default='workout', max_length=20, verbose_name='Иш-чаранын түрү')),
                ('client_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Кардардын аты')),
                ('club', models.CharField(default='Tribe', max_length=100, verbose_name='Клуб')),
                ('zone', models.CharField(default='Cycle', max_length=100, verbose_name='Зона')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Башталышы')),
                ('duration_min', models.PositiveIntegerField(default=30, verbose_name='Узактыгы (мүнөт)')),
                ('is_automatic_start', models.BooleanField(default=False, verbose_name='Автоматтык старт')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Видео шилтемеси')),
                ('music_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Музыка аты')),
                ('ftp_percent', models.PositiveIntegerField(default=70, verbose_name='FTP %')),
                ('cadence_range', models.CharField(default='65-70', max_length=50, verbose_name='Каденс диапазону')),
                ('status_active', models.BooleanField(default=False, verbose_name='Машыгуу башталды (Старт)')),
                ('current_interval', models.CharField(default='02:58', max_length=50, verbose_name='Интервал')),
                ('terrain_data', models.TextField(blank=True, null=True, verbose_name='Рельеф маалыматтары (График)')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.trainer', verbose_name='Тренер')),
                ('training_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.trainingtype', verbose_name='Машыгуу')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписаниелер',
            },
        ),
    ]
