# Generated by Django 6.0.2 on 2026-03-04 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='Сүрөт')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('visits_count', models.PositiveIntegerField(default=0, verbose_name='Кол-во посещений')),
                ('planned_lessons', models.PositiveIntegerField(default=0, verbose_name='Заплан. занятия')),
                ('last_visit', models.CharField(blank=True, max_length=100, null=True, verbose_name='Последн. посещение')),
                ('birth_date', models.CharField(max_length=100, verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('M', 'М'), ('W', 'Ж')], max_length=1, verbose_name='Пол')),
            ],
            options={
                'verbose_name': 'Пользователь системы',
                'verbose_name_plural': 'Пользователи системы',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('birth_date', models.CharField(max_length=100, verbose_name='Дата рождения (возраст)')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10, verbose_name='Пол')),
                ('weight', models.CharField(max_length=50, verbose_name='Вес (кг)')),
                ('ftp_w', models.PositiveIntegerField(default=0, verbose_name='FTP, w')),
                ('target_rpm', models.PositiveIntegerField(default=0, verbose_name='RPM')),
                ('target_watts', models.CharField(default='0W', max_length=50, verbose_name='Watts')),
                ('distance', models.CharField(default='0 км', max_length=50, verbose_name='Distance')),
                ('speed_kmh', models.PositiveIntegerField(default=0, verbose_name='Скорость км/ч')),
                ('calories', models.PositiveIntegerField(default=0, verbose_name='Калории')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активдүү')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Аты-жөнү')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Машыгуунун түрү')),
            ],
        ),
        migrations.CreateModel(
            name='VideoLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Аталышы')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('duration', models.CharField(max_length=50, verbose_name='Узактыгы')),
                ('preview', models.ImageField(upload_to='previews/', verbose_name='Превью сүрөтү')),
                ('video_file', models.FileField(upload_to='videos/', verbose_name='Видео файл')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Сүрөттөмө')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Видео китепканасы',
                'verbose_name_plural': 'Видео китепканалары',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('competition', 'Соревнование'), ('workout', 'Произвольная тренировка')], default='workout', max_length=20, verbose_name='Иш-чаранын түрү')),
                ('client_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Кардардын аты')),
                ('club', models.CharField(default='Tribe', max_length=100, verbose_name='Клуб')),
                ('zone', models.CharField(default='Cycle', max_length=100, verbose_name='Зона')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Башталышы')),
                ('duration_min', models.PositiveIntegerField(default=30, verbose_name='Узактыгы (мүнөт)')),
                ('is_automatic_start', models.BooleanField(default=False, verbose_name='Автоматтык старт')),
                ('ftp_percent', models.PositiveIntegerField(default=75, verbose_name='FTP, %')),
                ('cadence_range', models.CharField(default='67-70', max_length=50, verbose_name='RPM диапазону')),
                ('current_interval', models.CharField(default='05:00', max_length=50, verbose_name='Интервал убактысы')),
                ('terrain_data', models.JSONField(blank=True, default=list, verbose_name='График маалыматтары (Рельеф)')),
                ('music_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Музыка/Комментарий')),
                ('status_active', models.BooleanField(default=False, verbose_name='Машыгуу башталды (Старт)')),
                ('intervals_data', models.JSONField(blank=True, default=list, verbose_name='JSON маалыматтар')),
                ('participants', models.ManyToManyField(blank=True, to='schedule.appuser', verbose_name='Катышуучулар')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.trainer', verbose_name='Тренер')),
                ('training_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.trainingtype', verbose_name='Машыгуу')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.videolibrary', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписаниелер',
            },
        ),
    ]
